### ISSUE TITLE
Error while building on Linux

### ISSUE THREAD

**Issue by VioletWuff** [R3alCl0ud/Rust4Diva#21]
I'm having some issues to build the application on arch linux

after doing "cargo build" I'm getting these errors and it fails at the end

> warning: value assigned to `applied` is never read
> --> src/modmanagement.rs:278:17
> |
> 278 |         let mut applied = "".to_owned();
> |                 ^^^^^^^
> |
> = help: maybe it is overwritten before being read?
> = note: `#[warn(unused_assignments)]` on by default
> 
> warning: constant `GB_DIVA_SUBFEED` is never used
> --> src/gamebanana.rs:29:7
> |
> 29 | const GB_DIVA_SUBFEED: &str = "apiv11/Game/16522/Subfeed";
> |       ^^^^^^^^^^^^^^^
> |
> = note: `#[warn(dead_code)]` on by default
> 
> warning: field `itemtype` is never read
> --> src/gamebanana.rs:214:9
> |
> 212 | pub struct GbDmmItem {
> |            --------- field in this struct
> 213 |     pub item_id: i32,
> 214 |     pub itemtype: String,
> |         ^^^^^^^^
> |
> = note: `GbDmmItem` has derived impls for the traits `Debug` and `Clone`, but these are intentionally ignored during dead code analysis
> 
> warning: `rust4diva` (bin "rust4diva") generated 3 warnings
> Finished `dev` profile [unoptimized + debuginfo] target(s) in 2m 50s

OS: Garuda Linux x86_64
Kernel: Linux 6.10.10-zen1-1-zen
Shell: fish 3.7.1
Terminal: konsole 24.8.1

**Comment by R3alCl0ud** [comment]
Hi, those are warning messages and not errors. Just the compiler trying to be helpful.

**Comment by VioletWuff** [comment]
> Hi, those are warning messages and not errors. Just the compiler trying to be helpful. The logs say it built just fine, try `cargo run`

I see, thanks for the clarification!

**Comment by R3alCl0ud** [comment]
No problem, do not hesitate to post again if you find anything else concerning.

**Comment by VioletWuff** [comment]
> I see you are on Garuda. Do you need/want a copy of my PKGBUILDs for this? There is also a prebuilt for arch and it's derivatives uploaded on each release, just install that with `sudo pacman -U /path/to/rust4diva.pkg.tar.zst`

Yes you're right, it worked great like that.
Sorry I'm still kinda new on arch packages that I didn't know you can do that. Thanks for the help!
